#include <math.h>
#include <stdlib.h>
#include <stdio.h>

//computes the average and standard deviation of a sequence of N integers generated by the rand.

typedef int Number;
Number randNum(){ return rand(); }

main(int argc, char *argv[]){
    int i, N = atoi(argv[1]);
    float m1 = 0.0, m2 = 0.0;
    Number x;
    for(i = 0; i < N; i++){
        x = randNum(); //here, x is a number
        m1 += ((float) x) / N; //now it is a float in this operation
        m2 += ((float) x*x) / N;
    }
    printf("Average: %f\n", m1);
    printf("Stdev: %f\n", sqrt(m2-m1*m1));
}